GAME_NAME = "Pacman of MOAI Version"

--SCREEN_UNITS_X = 560
--SCREEN_UNITS_Y = 620
SCREEN_UNITS_X = 320 
SCREEN_UNITS_Y = 480
SCREEN_WIDTH = SCREEN_UNITS_X
SCREEN_HEIGHT = SCREEN_UNITS_Y

BASE_LOCATION_X = 0
BASE_LOCATION_Y = 0

FRAME_TIME = MOAISim:getFrameSize()

KEYBOARD_SPACE = 32
KEYBOARD_ENTER = 13

KEYBOARD_I = 105
KEYBOARD_J = 106
KEYBOARD_K = 107
KEYBOARD_L = 108

